##########################################################################
# 
# Basic Configuration
#

unbind C-x
set -g prefix C-x
bind C-x send-prefix
unbind C-b

# mouse usage off
set-option -g mouse off

# increase history limit
set-option -g history-limit 5000

# numbering windows and panes
set -g base-index 1 # start window number at 1
setw -g pane-base-index 1 # start pane number at 1

set -g renumber-windows on # if close a window, renumber the rest

# use 256 colors
set -g default-terminal 'screen-256color'
set -g terminal-overrides 'xterm:colors=256'

set -s escape-time 0

# status line color for message
set -g message-style fg=colour68,reverse,bg=brightwhite

# pain
set -g pane-active-border-style fg=colour111,bg=colour236
set -g pane-border-style fg=colour111,bg=colour236

##########################################################################
# 
# Key Bindings Configuration
#

# move pane
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# resize pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R 5

# apply vi mode to copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-selection

bind -n C-o select-pane -t :.+

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# split window
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
unbind '"'
unbind '%'

bind-key -T prefix r source-file ~/.config/tmux/tmux.conf \; display-message 'Reloard was successful.'

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

##########################################################################
# 
# Status Line Configuration
#

set -g status-justify absolute-centre
set -g status-position top
set -g status-interval 1

#  Contents
set -g status-fg white
set -g status-bg black

# Left side
set -g status-left-length 100
set -g status-left "#[fg=green]Session #S #[fg=yellow]Window #I #[fg=cyan]Pane: #P"

# Right side
set -g status-right-length 120
set -g status-right "#[fg=green,bg=default,bright]#(tmux-mem-cpu-load -a 0) "
set-option -ag status-right "#[fg=cyan][%Y-%m-%d(%a) %H:%M:%S]"

##########################################################################
# 
# Pane Configuration
#

# basic pane style
set -g window-style 'fg=white, bg=colour240'

#  active pane style
set -g window-active-style 'fg=white, bg=black'

